fix: github actions workflow
- consolidated linting and development branch testing to a single workflow `resource-development-branch.yml`
- moved testing of all resources and datasources from open PR's against main to the final provider binary build and release workflow `terraform-provider-release.yml`
- deleted old workflow artifacts: `lint.yml` & `intergration-tests-branch-pr.yml`

diff --git a/.github/workflows/resource-development-branch.yml b/.github/workflows/resource-development-branch.yml
--- a/.github/workflows/resource-development-branch.yml
+++ b/.github/workflows/resource-development-branch.yml
@@ -1,5 +1,5 @@
 # Terraform Provider testing workflow.
-name: golangci-lint
+name: resource development branch tests
 
 # This GitHub action runs your tests for each pull request and push.
 # Optionally, you can turn it on using a schedule for regular testing.
@@ -7,17 +7,17 @@ on:
   push:
     branches-ignore:
       - main
+      - development
     paths-ignore:
       - 'README.md'
 
+# Testing only needs permissions to read the repository contents.
 permissions:
   contents: read
-  # Optional: allow read access to pull request. Use with `only-new-issues` option.
-  # pull-requests: read
 
 jobs:
-  golangci:
-    name: lint
+  golangci-lint:
+    name: golangci-lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -58,3 +58,56 @@ jobs:
 
           # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
           # install-mode: "goinstall"
+
+  # Ensure project builds before running testing matrix
+  build:
+    name: build
+    needs: golangci-lint
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
+        with:
+          go-version-file: 'go.mod'
+          cache: true
+      - run: go mod download
+      - run: go build -v .
+
+  generate-docs:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
+        with:
+          go-version-file: 'go.mod'
+          cache: true
+      - run: go generate ./...
+      - name: git diff
+        run: |
+          git diff --compact-summary --exit-code || \
+            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
+
+  # Check test results and fail the workflow if the tests fail.
+  intergration_test:
+    needs: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check test result
+        run: |
+          changed_files=$(git diff --name-only $(git merge-base HEAD main))
+          test_function=$(grep -E '^func TestAcc.*\(t \*testing.T\)' $changed_files | awk -F 'func ' '{print $2}' | awk -F '(' '{print $1}')
+          if [[ -n "$test_function" ]]; then
+            # Run the test and store the output in a variable
+            test_output=$(go test -v -cover -run "$test_function" ./internal/provider/ 2>&1)
+            # Check if the test passed by searching for a specific pattern in the output
+            if echo "$test_output" | grep -q "PASS"; then
+              echo "TestAcc Passed"
+            else
+              echo "TestAcc Failed"
+              exit 1
+            fi
+          else
+            echo "TestAcc function not found"
+          fi
