test: github actions
test: github actions

diff --git a/.github/workflows/resource-development-branch.yml b/.github/workflows/resource-development-branch.yml
--- a/.github/workflows/resource-development-branch.yml
+++ b/.github/workflows/resource-development-branch.yml
@@ -91,6 +91,12 @@ jobs:
   tf-acc-resource-test:
     runs-on: ubuntu-latest
     timeout-minutes: 15
+    strategy:
+      fail-fast: false
+      matrix:
+        # list whatever Terraform versions here you would like to support
+        terraform:
+          - '1.2.*'
     steps:
       - name: Checkout development branch
         id: checkout-dev-branch
@@ -98,7 +104,7 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Set up Go Env
+      - name: Run tests on changed files
         id: go-env
         uses: actions/setup-go@v4
         with:
@@ -112,28 +118,27 @@ jobs:
         env:
           TF_ACC: "1"
           MERAKI_DASHBOARD_API_KEY: ${{ secrets.MERAKI_DASHBOARD_API_KEY }}
-
-      - name: Run tests on changed files
-        id: test-changed-files
-        run: |
-          
-          changed_files=$(git diff --name-only origin/main $GITHUB_HEAD_REF)
-          echo "changed files: $changed_files"
-          
-          acc_test_file=$(grep -E '^func TestAcc.*\(t \*testing.T\)' $changed_files | awk -F 'func ' '{print $2}' | awk -F '(' '{print $1}')
-          echo "acc test file: $acc_test_file"
-          
-          if [[ -n "$acc_test_file" ]]; then
-            # Run the test and store the output in a variable
-            test_output=$(go test -v -cover -run "$acc_test_file" ./internal/provider/ 2>&1)
-            # Check if the test passed by searching for a specific pattern in the output
-            if echo "$test_output" | grep -q "PASS"; then
-              echo "TestAcc Passed"
+          run: |
+            changed_files=$(git diff --name-only origin/main $GITHUB_HEAD_REF)
+            echo "changed files: $changed_files"
+            
+            acc_test_file=$(grep -E '^func TestAcc.*\(t \*testing.T\)' $changed_files | awk -F 'func ' '{print $2}' | awk -F '(' '{print $1}')
+            echo "acc test file: $acc_test_file"
+            
+            if [[ -n "$acc_test_file" ]]; then
+            
+              # Run the test and store the output in a variable
+              test_output=$(go test -v -cover -run "$acc_test_file" ./internal/provider/ 2>&1)
+            
+              # Check if the test passed by searching for a specific pattern in the output
+              echo "$test_output"
+              if echo "$test_output" | grep -q "PASS"; then
+                echo "TestAcc Passed"
+              else
+                echo "TestAcc Failed"
+                exit 1
+              fi
             else
-              echo "TestAcc Failed"
-              exit 1
+              echo "No test files found: $acc_test_file"
             fi
-          else
-            echo "No test files found: $acc_test_file"
-          fi
-        timeout-minutes: 10
+          timeout-minutes: 10
